### ISSUE TITLE
"error TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null" when generating a changelog

### ISSUE THREAD

**Issue by joshaber** [benogle/changelog#1]
```
$ pr-changelog -v -P -l ~/Documents/Development/GitHub/atom v1.3.3...v1.4.0 > changelog.md

Comparing atom/atom v1.3.3...v1.4.0
Local clone of repo /Users/joshaber/Documents/Development/GitHub/atom
Cannot fetch local commit diff, cannot find local copy of atom/atom
Found 250 commits from the GitHub API
Fetching PRs between dates 2015-11-17T22:00:30.000Z 2016-01-13T21:29:22.000Z
Fetching page 2
Fetching page 3
Found 74 merged PRs
No PR found for 9763 ; Commit text: Merge pull request #9763 from dranzerashi/patch-1

Generating dependency changelog for 'packageDependencies' on atom/atom

Comparing atom/one-dark-ui v1.1.5...v1.1.8
Found 20 commits from the GitHub API
Fetching PRs between dates 2015-08-15T10:14:16.000Z 2015-12-08T21:55:09.000Z
Found 11 merged PRs

Comparing atom/one-light-ui v1.1.5...v1.1.8
Found 19 commits from the GitHub API
Fetching PRs between dates 2015-08-15T10:16:42.000Z 2015-12-08T21:55:46.000Z
Found 11 merged PRs

Comparing atom/about v1.1.0...v1.3.0
Found 31 commits from the GitHub API
Fetching PRs between dates 2016-01-11T20:42:45.000Z 2016-01-13T18:28:52.000Z
Found 2 merged PRs

Comparing atom/autocomplete-plus v2.23.0...v2.25.0
Found 24 commits from the GitHub API
Fetching PRs between dates 2015-10-13T21:23:18.000Z 2015-12-18T22:08:03.000Z
Fetching page 2
Found 6 merged PRs

Comparing atom/autocomplete-snippets v1.8.0...v1.9.0
Found 3 commits from the GitHub API
Fetching PRs between dates 2015-11-25T01:20:25.000Z 2015-11-30T18:14:38.000Z
Found 1 merged PRs

Comparing atom/command-palette v0.37.0...v0.38.0
Found 2 commits from the GitHub API
Fetching PRs between dates 2015-12-15T21:59:09.000Z 2015-12-15T22:01:45.000Z
error TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
    at filter (/usr/local/lib/node_modules/pr-changelog/lib/utils.js:21:31)
    at getPullRequestsBetweenDates$ (/usr/local/lib/node_modules/pr-changelog/lib/changelog.js:214:21)
    at tryCatch (/usr/local/lib/node_modules/pr-changelog/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/pr-changelog/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/pr-changelog/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/pr-changelog/node_modules/babel-regenerator-runtime/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/pr-changelog/node_modules/core-js/modules/es6.promise.js:104:47)
    at /usr/local/lib/node_modules/pr-changelog/node_modules/core-js/modules/es6.promise.js:115:28
    at flush (/usr/local/lib/node_modules/pr-changelog/node_modules/core-js/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
```

**Comment by benogle** [comment]
FIxed in 88b8d7aa0977533d259fd11ee716d1b56227d80f

**Comment by benogle** [comment]
Also the readme was wrong, so you'll need to run the command with the `-r atom/atom` switch. I think that's why it wasnt finding your local copy of atom.

**Comment by joshaber** [comment]
:metal:
